### ISSUE TITLE
这个主题不能用了？安装启动后显示有致命错误

### ISSUE THREAD

**Issue by MemoryCollection** [Tokinx/iDevise-for-WordPress-Theme#1]

**Comment by Tokinx** [comment]
请提供更详细的信息，服务器系统、PHP版本、数据库等信息。

**Comment by MemoryCollection** [comment]
```
Fatal error: Uncaught Error: Call to undefined function create_function() in /www/wwwroot/blog.wi6.cn/wp-content/themes/iDevise-master/functions.php:175 Stack trace: #0 /www/wwwroot/blog.wi6.cn/wp-settings.php(672): include() #1 /www/wwwroot/blog.wi6.cn/wp-config.php(102): require_once('...') #2 /www/wwwroot/blog.wi6.cn/wp-load.php(50): require_once('...') #3 /www/wwwroot/blog.wi6.cn/wp-admin/admin.php(34): require_once('...') #4 /www/wwwroot/blog.wi6.cn/wp-admin/themes.php(10): require_once('...') #5 {main} thrown in /www/wwwroot/blog.wi6.cn/wp-content/themes/iDevise-master/functions.php on line 175

Warning: Trying to access array offset on value of type bool in /www/wwwroot/blog.wi6.cn/wp-includes/class-wp-recovery-mode-email-service.php on line 367

Warning: Trying to access array offset on value of type bool in /www/wwwroot/blog.wi6.cn/wp-includes/class-wp-recovery-mode-email-service.php on line 368
本网站出现严重错误。请查看网站管理员的邮件收件箱获取说明。如果仍有问题，请访问 [支持论坛](https://cn.wordpress.org/support/forums/)。

[了解有关对 WordPress 进行故障排除的更多信息。](https://wordpress.org/documentation/article/faq-troubleshooting/)
```

php 8.1 ,mysql 5.7.43 ,wordpress6.7.1

**Comment by MemoryCollection** [comment]
nginx nginx/1.24.0 
MySQL 5.7.43（最低要求：5.5.5） 
PHP 8.0.26（最低要求：7.2.24） 
Zend 4.0.26 
WordPress 6.7.1（58975） 
TinyMCE 49110-20201110
